### ISSUE TITLE
Branch?

### ISSUE THREAD

**Issue by darylteo** [bringnow/docker-git-sync#1]
Can we add a GIT_BRANCH env var to specify which branch to sync against?

Kind Regards,
Daryl

**Comment by christoph-jerolimov** [comment]
This is a great idea. Could you extend the sync.sh script and create a PR for this?

I expect that you should extend six git commands. Take a look for this subcommands: clone, remote, fetch (?), checkout, pull and push

**Comment by christoph-jerolimov** [comment]
Thank you for your PR #2 👍
